version: '3.7'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5430:5432
    environment:
      POSTGRES_DB: inss_crud_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .
    container_name: app
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/inss_crud
    ports:
      - "3000:3000"
    depends_on:
      - db
#      - yarn
    networks:
      - backend

#  yarn:
#    image: node:latest
#    container_name: yarn
#    restart: always
#    command: bash -c "tail -f dev/null"
#    volumes:
#      - .:/myapp

volumes:
  pgdata:

networks:
  backend: {}


# How connect with PGADMIN it --------------------------------------------------
# Access PgAdmin at broswer at locahost:{services.pgadmin.ports[0]}
# LOGGIN -----------------------------------------------------------------------
#      - login: {services.pgadmin.enviroment.PGADMIN_DEFAULT_EMAIL}
#      - password: {services.pgadmin.enviroment.PGADMIN_DEFAULT_PASSWORD}
# 
# REGISTER SERVICE STEP --------------------------------------------------------
# - GENERAL    - Name: choose a name
# ------------------------------------------------------------------------------
# - CONNECTION - Host: {services.postgres.container_name}
#              - Port: {services.postgres.ports[0]}
#              - Maintance database: {services.postgres.environment.POSTGRES_DB}
#              - Username: {services.postgres.environment.POSTGRES_USER}
#              - Password: {services.postgres.environment.POSTGRES_PASSWORD}
#-------------------------------------------------------------------------------
