version: '3.7'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5430:5432
    environment:
      POSTGRES_DB: inss_crud_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .
    container_name: app
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/inss_crud
    ports:
      - "3000:3000"
    depends_on:
      - db
#      - yarn
    networks:
      - backend
    stdin_open: true
    tty: true

volumes:
  pgdata:

networks:
  backend: {}
